//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


export class Vector2 {
    static deserializeFromJson(json: any): Vector2 {
        let x = json.x
        let y = json.y
        if (x == null || y == null) {
            throw new Error()
        }
        return new Vector2(x, y)
    }

    x: number
    y: number
    constructor(x: number = 0, y: number = 0) {
        this.x = x
        this.y = y
    }
}

export class Vector3 {
    static deserializeFromJson(json: any): Vector3 {
        let x = json.x
        let y = json.y
        let z = json.z
        if (x == null || y == null || z == null) {
            throw new Error()
        }
        return new Vector3(x, y, z)
    }

    x: number
    y: number
    z: number

    constructor(x: number = 0, y: number = 0, z: number = 0) {
        this.x = x
        this.y = y
        this.z = z
    }
}

export class Vector4 {
    static deserializeFromJson(json: any): Vector4 {
        let x = json.x
        let y = json.y
        let z = json.z
        let w = json.w
        if (x == null || y == null || z == null || w == null) {
            throw new Error()
        }
        return new Vector4(x, y, z, w)
    }
    
    x: number
    y: number
    z: number
    w: number

    constructor(x: number = 0, y: number = 0, z: number = 0, w: number = 0) {
        this.x = x
        this.y = y
        this.z = z
        this.w = w
    }
}



export enum UnitType {
    /**
     * 玩家
     */
    Player = 1,
    /**
     * 怪物
     */
    Monster = 2,
    NPC = 3,
}



export enum NumericType {
    Speed = 1000,
    AOI = 1002,
}



export class UnitConfigCategory{
    private _dataMap: Map<number, UnitConfig>
    private _dataList: UnitConfig[]
    constructor(_json_: any) {
        this._dataMap = new Map<number, UnitConfig>()
        this._dataList = []
        for(var _json2_ of _json_) {
            let _v: UnitConfig
            _v = new UnitConfig(_json2_)
            this._dataList.push(_v)
            this._dataMap.set(_v.Id, _v)
        }
    }

    getDataMap(): Map<number, UnitConfig> { return this._dataMap; }
    getDataList(): UnitConfig[] { return this._dataList; }

    get(key: number): UnitConfig | undefined { return this._dataMap.get(key); }

    resolve(_tables: Map<string, any>) {
        for(var v of this._dataList) {
            v.resolve(_tables)
        }

        //@ts-ignore
        if (this.afterEndInit) {
            //@ts-ignore
            this.afterEndInit()
        }
    }

}





export class UnitConfig {

    constructor(_json_: any) {
        if (_json_.Id === undefined) { throw new Error() }
        this.Id = _json_.Id
        if (_json_.Type === undefined) { throw new Error() }
        this.Type = _json_.Type
        if (_json_.Name === undefined) { throw new Error() }
        this.Name = _json_.Name
        if (_json_.Desc === undefined) { throw new Error() }
        this.Desc = _json_.Desc
    }

    /**
     * id
     */
    readonly Id: number
    /**
     * 类型
     */
    readonly Type: UnitType
    /**
     * 名字
     */
    readonly Name: string
    /**
     * 描述
     */
    readonly Desc: string

    resolve(_tables: Map<string, any>) {

        //@ts-ignore
        if (this.afterEndInit) {
            //@ts-ignore
            this.afterEndInit()
        }
    }
}




export class ItemConfigCategory{
    private _dataMap: Map<number, ItemConfig>
    private _dataList: ItemConfig[]
    constructor(_json_: any) {
        this._dataMap = new Map<number, ItemConfig>()
        this._dataList = []
        for(var _json2_ of _json_) {
            let _v: ItemConfig
            _v = new ItemConfig(_json2_)
            this._dataList.push(_v)
            this._dataMap.set(_v.id, _v)
        }
    }

    getDataMap(): Map<number, ItemConfig> { return this._dataMap; }
    getDataList(): ItemConfig[] { return this._dataList; }

    get(key: number): ItemConfig | undefined { return this._dataMap.get(key); }

    resolve(_tables: Map<string, any>) {
        for(var v of this._dataList) {
            v.resolve(_tables)
        }

        //@ts-ignore
        if (this.afterEndInit) {
            //@ts-ignore
            this.afterEndInit()
        }
    }

}





export class ItemConfig {

    constructor(_json_: any) {
        if (_json_.id === undefined) { throw new Error() }
        this.id = _json_.id
        if (_json_.name === undefined) { throw new Error() }
        this.name = _json_.name
        if (_json_.desc === undefined) { throw new Error() }
        this.desc = _json_.desc
        if (_json_.price === undefined) { throw new Error() }
        this.price = _json_.price
        if (_json_.upgrade_to_item_id === undefined) { throw new Error() }
        this.upgradeToItemId = _json_.upgrade_to_item_id
        if(_json_.expire_time != undefined) { this.expireTime = _json_.expire_time } else { this.expireTime = undefined }
        if (_json_.batch_useable === undefined) { throw new Error() }
        this.batchUseable = _json_.batch_useable
        if (_json_.exchange_stream === undefined) { throw new Error() }
        this.exchangeStream = _json_.exchange_stream
        if (_json_.exchange_list === undefined) { throw new Error() }
        this.exchangeList = _json_.exchange_list
    }

    /**
     * 这是id
     */
    readonly id: number
    /**
     * 名字
     */
    readonly name: string
    /**
     * 描述
     */
    readonly desc: string
    /**
     * 价格
     */
    readonly price: number
    /**
     * 引用当前表
     */
    readonly upgradeToItemId: number
    /**
     * 过期时间
     */
    readonly expireTime: number|undefined
    /**
     * 能否批量使用
     */
    readonly batchUseable: boolean
    /**
     * 道具兑换配置
     */
    readonly exchangeStream: string
    readonly exchangeList: string

    resolve(_tables: Map<string, any>) {

        //@ts-ignore
        if (this.afterEndInit) {
            //@ts-ignore
            this.afterEndInit()
        }
    }
}




type JsonLoader = (file: Array<string>) => any

export class Tables {
    private static _UnitConfigCategory: UnitConfigCategory
    static get UnitConfigCategory(): UnitConfigCategory  { return this._UnitConfigCategory;}
    private static _ItemConfigCategory: ItemConfigCategory
    static get ItemConfigCategory(): ItemConfigCategory  { return this._ItemConfigCategory;}

    public static async init(loader: JsonLoader) {
        let tables = new Map<string, any>()
        let loadList: Array<string> = new Array

        loadList.push('unitconfigcategory')
        loadList.push('itemconfigcategory')

        let dataMap: Map<string, any> = await loader(loadList)

        this._UnitConfigCategory = new UnitConfigCategory(dataMap.get('unitconfigcategory'))
        tables.set('UnitConfigCategory', this._UnitConfigCategory)
        this._ItemConfigCategory = new ItemConfigCategory(dataMap.get('itemconfigcategory'))
        tables.set('ItemConfigCategory', this._ItemConfigCategory)

        this._UnitConfigCategory.resolve(tables)
        this._ItemConfigCategory.resolve(tables)
    }
}
